spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3310/AuthDB?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: 413D111FBFB399AA704EC2F2B9E976CEBE57B295EFAF7DD868F696DE772935537EB0FA9B67B5D2D151CF465AD36942566AD55CBCE100EED2BFA25A8D03EE4263
