spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${BASE_URL}:${AUTH_SERVICE_SERVER_PORT}
          predicates:
            - Path=/auth/**

        - id: profile-service
          uri: ${BASE_URL}:${PROFILE_SERVICE_SERVER_PORT}
          predicates:
            - Path=/profile/**

        - id: notification-service
          uri: ${BASE_URL}:${NOTIFICATION_SERVICE_SERVER_PORT}
          predicates:
            - Path=/notification/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
server:
  port: ${GATEWAY_SERVICE_SERVER_PORT}