spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${BASE_URL}:${AUTH_SERVICE_SERVER_PORT}
          predicates:
            - Path=/auth/**

        - id: profile-service
          uri: ${BASE_URL}:${PROFILE_SERVICE_SERVER_PORT}
          predicates:
            - Path=/profile/**

        - id: notification-service
          uri: ${BASE_URL}:${NOTIFICATION_SERVICE_SERVER_PORT}
          predicates:
            - Path=/notification/**

        - id: booking-service
          uri: ${BASE_URL}:${BOOKING_SERVICE_SERVER_PORT}
          predicates:
            - Path=/booking/**

        - id: coach-service
          uri: ${BASE_URL}:${COACH_SERVICE_SERVER_PORT}
          predicates:
            - Path=/coach/**

        - id: company-service
          uri: ${BASE_URL}:${COMPANY_SERVICE_SERVER_PORT}
          predicates:
            - Path=/company/**

        - id: driver-service
          uri: ${BASE_URL}:${DRIVER_SERVICE_SERVER_PORT}
          predicates:
            - Path=/driver/**

        - id: payment-service
          uri: ${BASE_URL}:${PAYMENT_SERVICE_SERVER_PORT}
          predicates:
            - Path=/payment/**

        - id: route-service
          uri: ${BASE_URL}:${ROUTE_SERVICE_SERVER_PORT}
          predicates:
            - Path=/route/**

        - id: trip-service
          uri: ${BASE_URL}:${TRIP_SERVICE_SERVER_PORT}
          predicates:
            - Path=/trip/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}


server:
  port: ${GATEWAY_SERVICE_SERVER_PORT}