spring:
  application:
    name: booking-service

  data:
    mongodb:
      uri: ${BOOKING_SERVICE_DB_URL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}

server:
  port: ${BOOKING_SERVICE_SERVER_PORT}