spring:
  application:
    name: profile-service
  neo4j:
    uri: ${PROFILE_SERVICE_DB_URL}
    authentication:
      username: ${PROFILE_SERVICE_DB_USERNAME}
      password: ${PROFILE_SERVICE_DB_PASSWORD}
server:
  port: ${PROFILE_SERVICE_SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui